<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="29275" started-at="2019-09-09T10:36:38Z" finished-at="2019-09-09T10:37:07Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="29275" started-at="2019-09-09T10:36:38Z" finished-at="2019-09-09T10:37:07Z">
      <class name="com.capability.qa.testcases.LoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.capability.qa.testcases.LoginTest@6dc17b83]" name="setUp" is-config="true" duration-ms="14305" started-at="2019-09-09T16:06:38Z" finished-at="2019-09-09T16:06:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginPageTitleTest()[pri:1, instance:com.capability.qa.testcases.LoginTest@6dc17b83]" name="loginPageTitleTest" duration-ms="32" started-at="2019-09-09T16:06:52Z" finished-at="2019-09-09T16:06:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Admin Console] but found [Capability App]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Admin Console] but found [Capability App]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.capability.qa.testcases.LoginTest.loginPageTitleTest(LoginTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.capability.qa.testcases.LoginTest@6dc17b83]" name="tearDown" is-config="true" duration-ms="767" started-at="2019-09-09T16:06:52Z" finished-at="2019-09-09T16:06:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.capability.qa.testcases.LoginTest@6dc17b83]" name="setUp" is-config="true" duration-ms="12781" started-at="2019-09-09T16:06:53Z" finished-at="2019-09-09T16:07:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginTest()[pri:2, instance:com.capability.qa.testcases.LoginTest@6dc17b83]" name="loginTest" duration-ms="614" started-at="2019-09-09T16:07:05Z" finished-at="2019-09-09T16:07:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.capability.qa.testcases.LoginTest@6dc17b83]" name="tearDown" is-config="true" duration-ms="727" started-at="2019-09-09T16:07:06Z" finished-at="2019-09-09T16:07:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.capability.qa.testcases.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
